<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
#train = pd.read_csv('train.csv')
train = pd.read_csv('test.csv')

In [2]:
train.head(10)

id    host_id         host_name  latitude  longitude  \
0  21399885   96664487            Hupeto  40.68742  -73.91628   
1  35037136  120111937  Madea And Julian  40.70865  -73.96673   
2  13330602   27977872              Dana  40.70716  -74.01155   
3  33951037  254472726            Jerick  40.73198  -74.00526   
4  28692911   12166742             Yizak  40.62515  -73.94409   
5  28389754   23120620            Jackie  40.73862  -73.80808   
6  24348078  176427055              Adam  40.76649  -73.92643   
7   4660022     745486                Re  40.72592  -73.99933   
8  23172490  117108525               Sen  40.74759  -73.91446   
9   9345056   16963843           Martina  40.69902  -73.92195   

         room_type  minimum_nights  number_of_reviews last_review  \
0  Entire home/apt               3                 26  2019-06-18   
1  Entire home/apt              30                  5  2019-06-23   
2  Entire home/apt               5                  0         NaN   
3  Entire home/apt              31                  5  2019-05-23   
4  Entire home/apt               1                 21  2019-07-05   
5     Private room               1                  2  2019-05-20   
6     Private room               1                102  2019-07-07   
7  Entire home/apt               1                 66  2019-06-24   
8     Private room               1                 78  2019-06-28   
9     Private room               5                 28  2018-08-20   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               1.41                               3               341  
1               3.33                               1               333  
2                NaN                               1                 0  
3               1.92                               1               219  
4               2.26                               1                82  
5               0.52                               5                90  
6               6.77                               1               348  
7               1.18                               1               365  
8               4.62                               2               116  
9               1.36                               2                 0

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7824 entries, 0 to 7823
Data columns (total 12 columns):
id                                7824 non-null int64
host_id                           7824 non-null int64
host_name                         7820 non-null object
latitude                          7824 non-null float64
longitude                         7824 non-null float64
room_type                         7824 non-null object
minimum_nights                    7824 non-null int64
number_of_reviews                 7824 non-null int64
last_review                       6295 non-null object
reviews_per_month                 6295 non-null float64
calculated_host_listings_count    7824 non-null int64
availability_365                  7824 non-null int64
dtypes: float64(3), int64(6), object(3)
memory usage: 733.6+ KB


In [4]:
train.describe()

id       host_id     latitude    longitude  minimum_nights  \
count  7.824000e+03  7.824000e+03  7824.000000  7824.000000     7824.000000   
mean   1.890081e+07  6.764486e+07    40.729073   -73.951980        7.269427   
std    1.104529e+07  7.895703e+07     0.053794     0.046807       21.015574   
min    5.099000e+03  2.787000e+03    40.508680   -74.244420        1.000000   
25%    9.351911e+06  7.611178e+06    40.690845   -73.983272        1.000000   
50%    1.956433e+07  3.042285e+07    40.723535   -73.955800        3.000000   
75%    2.919030e+07  1.074344e+08    40.763015   -73.936858        5.000000   
max    3.648543e+07  2.741034e+08    40.911670   -73.719280      500.000000   

       number_of_reviews  reviews_per_month  calculated_host_listings_count  \
count        7824.000000        6295.000000                     7824.000000   
mean           24.248594           1.380986                        6.995527   
std            46.532751           1.647855                       32.709043   
min             0.000000           0.010000                        1.000000   
25%             1.000000           0.185000                        1.000000   
50%             5.000000           0.730000                        1.000000   
75%            24.000000           2.050000                        2.000000   
max           458.000000          16.030000                      327.000000   

       availability_365  
count       7824.000000  
mean         114.468430  
std          132.209046  
min            0.000000  
25%            0.000000  
50%           49.000000  
75%          229.000000  
max          365.000000

In [13]:
train.shape

(7824, 12)

In [14]:
train.isna().sum()

id                                   0
host_id                              0
host_name                            4
latitude                             0
longitude                            0
room_type                            0
minimum_nights                       0
number_of_reviews                    0
last_review                       1529
reviews_per_month                 1529
calculated_host_listings_count       0
availability_365                     0
dtype: int64

In [15]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7824 entries, 0 to 7823
Data columns (total 12 columns):
id                                7824 non-null int64
host_id                           7824 non-null int64
host_name                         7820 non-null object
latitude                          7824 non-null float64
longitude                         7824 non-null float64
room_type                         7824 non-null object
minimum_nights                    7824 non-null int64
number_of_reviews                 7824 non-null int64
last_review                       6295 non-null object
reviews_per_month                 6295 non-null float64
calculated_host_listings_count    7824 non-null int64
availability_365                  7824 non-null int64
dtypes: float64(3), int64(6), object(3)
memory usage: 733.6+ KB


In [16]:
continuous = ['minimum_nights ', 'number_of_reviews ', 'calculated_host_listings_count ', 'availability_365 ']
categoricals =  ['room_type']

In [18]:
train.duplicated().sum()

0

In [19]:
df = train.drop(['latitude', 'longitude', 'id', 'host_id', 'host_name', 'last_review', 'reviews_per_month'], axis=1)
display(df.head())



room_type  minimum_nights  number_of_reviews  \
0  Entire home/apt               3                 26   
1  Entire home/apt              30                  5   
2  Entire home/apt               5                  0   
3  Entire home/apt              31                  5   
4  Entire home/apt               1                 21   

   calculated_host_listings_count  availability_365  
0                               3               341  
1                               1               333  
2                               1                 0  
3                               1               219  
4                               1                82

In [20]:
#y = train['price']
#display(y.head())

In [21]:
dummies = pd.get_dummies(df['room_type'], prefix=categoricals, drop_first=True)



X = pd.concat([df, dummies], axis=1)
X = X.drop(['room_type'], axis=1)

X.head()

minimum_nights  number_of_reviews  calculated_host_listings_count  \
0               3                 26                               3   
1              30                  5                               1   
2               5                  0                               1   
3              31                  5                               1   
4               1                 21                               1   

   availability_365  ['room_type']_Private room  ['room_type']_Shared room  
0               341                           0                          0  
1               333                           0                          0  
2                 0                           0                          0  
3               219                           0                          0  
4                82                           0                          0

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

NameError: name 'y' is not defined

In [23]:
features = X_train
labels = y_train

NameError: name 'X_train' is not defined

In [24]:
X_train.head()

NameError: name 'X_train' is not defined

In [75]:
from sklearn.linear_model import LinearRegression

my_model = LinearRegression()
my_model.fit(features, labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [76]:
from sklearn.metrics import mean_squared_error

predictions = my_model.predict(features)
mse = mean_squared_error(labels, predictions)
rmse = np.sqrt(mse)

print(rmse)

203.5018303408126


In [77]:
display(my_model.coef_)

array([-9.99496440e-02, -3.47836552e-01,  3.11094427e-02,  1.76739681e-01,
       -1.22472264e+02, -1.49474293e+02])

In [78]:
display(my_model.intercept_)

200.26662618367692

In [79]:
my_model.coef_.reshape(-1,1)

array([[-9.99496440e-02],
       [-3.47836552e-01],
       [ 3.11094427e-02],
       [ 1.76739681e-01],
       [-1.22472264e+02],
       [-1.49474293e+02]])

In [80]:
pd.DataFrame(data=my_model.coef_.reshape(1, -1), columns=features.columns)

minimum_nights  number_of_reviews  calculated_host_listings_count  \
0        -0.09995          -0.347837                        0.031109   

   availability_365  ['room_type']_Private room  ['room_type']_Shared room  
0           0.17674                 -122.472264                -149.474293

In [81]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
            my_model, 
            features,
            labels,
            cv=10,
            scoring="neg_mean_squared_error"
)

rmse_scores = np.sqrt(-scores)
display(rmse_scores)
display(rmse_scores.mean())
display(rmse_scores.std())

array([243.39464847, 232.72990506, 179.02823436, 186.777091  ,
       163.38592079, 242.00186954, 200.783307  , 145.10668338,
       188.92960087, 227.36341527])

200.950067571588

32.48064661698816

In [82]:
y.std()

221.59490965154006

In [83]:
from statsmodels.formula.api import ols

In [88]:
y_values = y.values
X_values = X.values

In [103]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31284 entries, 0 to 31291
Data columns (total 6 columns):
minimum_nights                    31284 non-null int64
number_of_reviews                 31284 non-null int64
calculated_host_listings_count    31284 non-null int64
availability_365                  31284 non-null int64
['room_type']_Private room        31284 non-null uint8
['room_type']_Shared room         31284 non-null uint8
dtypes: int64(4), uint8(2)
memory usage: 1.3 MB


In [110]:
final = X.copy()

In [119]:
import statsmodels.api as sm
df_inter_sm = sm.add_constant(final)
model = sm.OLS(y,final)
results = model.fit()

results.summary()

/Users/badmin/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.127
Model:                            OLS   Adj. R-squared (uncentered):              0.127
Method:                 Least Squares   F-statistic:                              909.3
Date:                Sun, 26 Apr 2020   Prob (F-statistic):                        0.00
Time:                        14:42:32   Log-Likelihood:                     -2.1720e+05
No. Observations:               31284   AIC:                                  4.344e+05
Df Residuals:                   31279   BIC:                                  4.345e+05
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
minimum_nights                     2.1077      0.071     29.546      0.000       1.968       2.248
number_of_reviews                  0.8831      0.030     29.102      0.000       0.824       0.943
calculated_host_listings_count     0.9867      0.043     22.974      0.000       0.903       1.071
['room_type']_Private room        54.6501      2.239     24.413      0.000      50.262      59.038
['room_type']_Shared room         37.4565      9.078      4.126      0.000      19.663      55.251
==============================================================================
Omnibus:                    57852.141   Durbin-Watson:                   1.776
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        177455456.848
Skew:                          13.643   Prob(JB):                         0.00
Kurtosis:                     370.958   Cond. No.                         317.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [114]:
X_test.shape

(6257, 6)

In [115]:
y_hat.shape

(6257,)

In [117]:
y_hat = my_model.predict(X_test)
y_hat

array([102.46648481, 199.1023143 , 185.69950279, ..., 223.9869381 ,
       210.74961643,  77.7255221 ])

In [118]:
residuals = y_hat - y_test
residuals.head(25)

2471     -36.533515
15572     -0.897686
15932     11.699503
31214   -124.062547
641      -75.890524
10154     25.538553
937       66.607071
29264    -23.307731
29342     12.177786
14904     -0.749748
1207     140.611633
8913      81.665334
20843    -19.529028
18388     -2.084432
1381      74.897133
3257      70.197786
15373     80.104194
20310   -150.287731
10830     32.033436
4183     141.274935
13350    -33.529716
10247     82.384951
30284     58.428625
5366      52.511069
26704     75.846670
Name: price, dtype: float64