<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [44]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
train = pd.read_csv('test.csv')


In [45]:
train.head(10)

id    host_id         host_name  latitude  longitude  \
0  21399885   96664487            Hupeto  40.68742  -73.91628   
1  35037136  120111937  Madea And Julian  40.70865  -73.96673   
2  13330602   27977872              Dana  40.70716  -74.01155   
3  33951037  254472726            Jerick  40.73198  -74.00526   
4  28692911   12166742             Yizak  40.62515  -73.94409   
5  28389754   23120620            Jackie  40.73862  -73.80808   
6  24348078  176427055              Adam  40.76649  -73.92643   
7   4660022     745486                Re  40.72592  -73.99933   
8  23172490  117108525               Sen  40.74759  -73.91446   
9   9345056   16963843           Martina  40.69902  -73.92195   

         room_type  minimum_nights  number_of_reviews last_review  \
0  Entire home/apt               3                 26  2019-06-18   
1  Entire home/apt              30                  5  2019-06-23   
2  Entire home/apt               5                  0         NaN   
3  Entire home/apt              31                  5  2019-05-23   
4  Entire home/apt               1                 21  2019-07-05   
5     Private room               1                  2  2019-05-20   
6     Private room               1                102  2019-07-07   
7  Entire home/apt               1                 66  2019-06-24   
8     Private room               1                 78  2019-06-28   
9     Private room               5                 28  2018-08-20   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               1.41                               3               341  
1               3.33                               1               333  
2                NaN                               1                 0  
3               1.92                               1               219  
4               2.26                               1                82  
5               0.52                               5                90  
6               6.77                               1               348  
7               1.18                               1               365  
8               4.62                               2               116  
9               1.36                               2                 0

In [46]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7824 entries, 0 to 7823
Data columns (total 12 columns):
id                                7824 non-null int64
host_id                           7824 non-null int64
host_name                         7820 non-null object
latitude                          7824 non-null float64
longitude                         7824 non-null float64
room_type                         7824 non-null object
minimum_nights                    7824 non-null int64
number_of_reviews                 7824 non-null int64
last_review                       6295 non-null object
reviews_per_month                 6295 non-null float64
calculated_host_listings_count    7824 non-null int64
availability_365                  7824 non-null int64
dtypes: float64(3), int64(6), object(3)
memory usage: 733.6+ KB


In [47]:
train.describe()

id       host_id     latitude    longitude  minimum_nights  \
count  7.824000e+03  7.824000e+03  7824.000000  7824.000000     7824.000000   
mean   1.890081e+07  6.764486e+07    40.729073   -73.951980        7.269427   
std    1.104529e+07  7.895703e+07     0.053794     0.046807       21.015574   
min    5.099000e+03  2.787000e+03    40.508680   -74.244420        1.000000   
25%    9.351911e+06  7.611178e+06    40.690845   -73.983272        1.000000   
50%    1.956433e+07  3.042285e+07    40.723535   -73.955800        3.000000   
75%    2.919030e+07  1.074344e+08    40.763015   -73.936858        5.000000   
max    3.648543e+07  2.741034e+08    40.911670   -73.719280      500.000000   

       number_of_reviews  reviews_per_month  calculated_host_listings_count  \
count        7824.000000        6295.000000                     7824.000000   
mean           24.248594           1.380986                        6.995527   
std            46.532751           1.647855                       32.709043   
min             0.000000           0.010000                        1.000000   
25%             1.000000           0.185000                        1.000000   
50%             5.000000           0.730000                        1.000000   
75%            24.000000           2.050000                        2.000000   
max           458.000000          16.030000                      327.000000   

       availability_365  
count       7824.000000  
mean         114.468430  
std          132.209046  
min            0.000000  
25%            0.000000  
50%           49.000000  
75%          229.000000  
max          365.000000

In [50]:
train.isna().sum()

id                                   0
host_id                              0
host_name                            4
latitude                             0
longitude                            0
room_type                            0
minimum_nights                       0
number_of_reviews                    0
last_review                       1529
reviews_per_month                 1529
calculated_host_listings_count       0
availability_365                     0
dtype: int64

In [51]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7824 entries, 0 to 7823
Data columns (total 12 columns):
id                                7824 non-null int64
host_id                           7824 non-null int64
host_name                         7820 non-null object
latitude                          7824 non-null float64
longitude                         7824 non-null float64
room_type                         7824 non-null object
minimum_nights                    7824 non-null int64
number_of_reviews                 7824 non-null int64
last_review                       6295 non-null object
reviews_per_month                 6295 non-null float64
calculated_host_listings_count    7824 non-null int64
availability_365                  7824 non-null int64
dtypes: float64(3), int64(6), object(3)
memory usage: 733.6+ KB


In [52]:
continuous = ['minimum_nights ', 'number_of_reviews ', 'calculated_host_listings_count ', 'availability_365 ']
categoricals =  ['room_type']

In [14]:
train.duplicated().sum()

0

In [53]:
df = train.drop(['latitude', 'longitude', 'id', 'host_id', 'host_name', 'last_review', 'reviews_per_month'], axis=1)
display(df.head())



room_type  minimum_nights  number_of_reviews  \
0  Entire home/apt               3                 26   
1  Entire home/apt              30                  5   
2  Entire home/apt               5                  0   
3  Entire home/apt              31                  5   
4  Entire home/apt               1                 21   

   calculated_host_listings_count  availability_365  
0                               3               341  
1                               1               333  
2                               1                 0  
3                               1               219  
4                               1                82

In [55]:
dummies = pd.get_dummies(df['room_type'], prefix=categoricals, drop_first=True)



X = pd.concat([df, dummies], axis=1)
X = X.drop(['room_type'], axis=1)

X.head()

minimum_nights  number_of_reviews  calculated_host_listings_count  \
0               3                 26                               3   
1              30                  5                               1   
2               5                  0                               1   
3              31                  5                               1   
4               1                 21                               1   

   availability_365  ['room_type']_Private room  ['room_type']_Shared room  
0               341                           0                          0  
1               333                           0                          0  
2                 0                           0                          0  
3               219                           0                          0  
4                82                           0                          0

In [56]:
X = X.drop(X.columns[-1], axis=1)

In [19]:
features = X


In [24]:
my_model.coef_.reshape(-1,1)

array([[ 5.01837980e-02],
       [-3.05384944e-01],
       [ 8.15568631e-02],
       [ 1.45246542e-01],
       [-1.11956890e+02]])

In [25]:
pd.DataFrame(data=my_model.coef_.reshape(1, -1), columns=features.columns)

minimum_nights  number_of_reviews  calculated_host_listings_count  \
0        0.050184          -0.305385                        0.081557   

   availability_365  ['room_type']_Private room  
0          0.145247                  -111.95689

In [26]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
            my_model, 
            features,
            labels,
            cv=10,
            scoring="neg_mean_squared_error"
)

rmse_scores = np.sqrt(-scores)
display(rmse_scores)
display(rmse_scores.mean())
display(rmse_scores.std())

array([237.06074261, 272.09692762, 211.16162448, 127.95841448,
       213.80386265, 250.78704419, 192.81628294, 214.80802016,
       185.41772161, 191.92529048])

209.78359312233277

37.74579193463584

In [27]:
y.std()

221.59490965154006

In [28]:
from statsmodels.formula.api import ols

In [29]:
y_values = y.values
X_values = X.values

In [36]:
final = X

In [37]:
import statsmodels.api as sm
df_inter_sm = sm.add_constant(final)
model = sm.OLS(y,final)
results = model.fit()

results.summary()

/Users/badmin/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  price   R-squared (uncentered):                   0.190
Model:                            OLS   Adj. R-squared (uncentered):              0.190
Method:                 Least Squares   F-statistic:                              1469.
Date:                Sun, 26 Apr 2020   Prob (F-statistic):                        0.00
Time:                        15:27:14   Log-Likelihood:                     -2.1603e+05
No. Observations:               31284   AIC:                                  4.321e+05
Df Residuals:                   31279   BIC:                                  4.321e+05
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
minimum_nights                     1.2591      0.071     17.787      0.000       1.120       1.398
number_of_reviews                  0.3573      0.031     11.493      0.000       0.296       0.418
calculated_host_listings_count     0.3808      0.043      8.828      0.000       0.296       0.465
availability_365                   0.5017      0.010     49.615      0.000       0.482       0.522
['room_type']_Private room        18.1483      2.276      7.975      0.000      13.688      22.609
==============================================================================
Omnibus:                    59013.747   Durbin-Watson:                   1.841
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        206754619.870
Skew:                          14.225   Prob(JB):                         0.00
Kurtosis:                     400.248   Cond. No.                         291.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [38]:
y_hat = my_model.predict(X)
y_hat

array([192.08007592,  80.68377192, 131.97228262, ..., 188.39664586,
       193.71307983, 189.94238131])

In [39]:
y_hat.shape

(31284,)

In [40]:
residuals = y_hat - y
residuals.head(25)

0    -187.919924
1      17.683772
2      54.972283
3    -207.467478
4       6.174437
5      27.428571
6      50.679490
7     125.808352
8      23.806145
9     -36.293440
10      9.244139
11   -207.309154
12     17.640662
13     73.786932
14   -182.108419
15     24.736047
16      7.722984
17    152.967700
18     35.512416
19    102.770006
20     50.178182
21      2.473899
22    106.965182
23      7.346462
24    -57.309154
Name: price, dtype: float64

In [41]:
residuals.shape

(31284,)

In [42]:
test.shape

(7824, 12)

In [43]:
import joblib

joblib.dump(my_model, "my_model_abnb.pkl")

['my_model_abnb.pkl']